language: java

jdk:
  - oraclejdk8

services:
  - postgresql

postgres:
  adapter: postgresql
  database: spontandb
  username: spontanu
  password: spontap

before-script:
  - psql -c 'create schema spontan;' -U postgres -d spontandb